superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hero_id>/', views.detail, name = 'detail'),
    path('new/', views.create, name = 'create'),
    path('edit/<int:hero_id>/', views.edit, name = 'edit'),
    path('delete/<int:hero_id>/', views.delete, name = 'delete')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)


    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk = hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        #Save form contents as a new db object
        #return to index
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    if request.method == "POST":
        single_hero = Superhero.objects.get(pk = hero_id)
        single_hero.name = request.POST.get('name')
        single_hero.alter_ego = request.POST.get('alter_ego')
        single_hero.primary = request.POST.get('primary')
        single_hero.secondary = request.POST.get('secondary')
        single_hero.catchphrase = request.POST.get('catchphrase')
        single_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else :
        single_hero = Superhero.objects.get(pk = hero_id)
        context = {
        'single_hero': single_hero
        }
        return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    if request.method == "POST":
        single_hero = Superhero.objects.get(pk = hero_id)
        single_hero.delete()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        single_hero = Superhero.objects.get(pk = hero_id)
        context = {
            'single_hero': single_hero
        }
        return render(request, 'superheroes/delete.html', context)

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type = "text" name = "name" id = "name"><br />
        Alter Ego: <input type = "text" name = "alter_ego" id = "alter_ego"><br />
        Primary Ability: <input type = "text" name = "primary" id = "primary"><br />
        Secondary Ability: <input type = "text" name = "secondary" id = "secondary"><br />
        Catchphrase: <input type = "text" name = "catchphrase" id = "catch_phrase"><br />
        <input type = "submit" value = "Add!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Superhero</title>
</head>
<body>
    <h1>Are you sure you want to delete {{single_hero.name}}?</h1>
    <form action = "{% url 'superheroes:delete' single_hero.id %}" method = "post">
        {% csrf_token %}
        <input type = "submit" value = "Delete">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Detail</title>
</head>
<body>
    <h1>{{single_hero.name}} Details</h1>
    <ul>
        <li> <h2>{{single_hero.name}}</h2> </li>
        <li> <h2>{{single_hero.alter_ego}}</h2> </li>
        <li> <h2>{{single_hero.primary_ability}}</h2> </li>
        <li> <h2>{{single_hero.secondary_ability}}</h2> </li>
        <li> <h2>{{single_hero.catch_phrase}}</h2> </li>
    </ul>
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Superhero</title>
</head>
<body>
    <h1>Edit {{single_hero.name}} </h1>
    <form action = "{% url 'superheroes:edit' single_hero.id %}" method="post">
        {% csrf_token %}
        New Name: <input type = "text" name = "name" id = "name" value = "{{single_hero.name}}"><br />
        New Alter Ego: <input type = "text" name = "alter_ego" id = "alter_ego" value = "{{single_hero.alter_ego}}"><br />
        New Primary Ability: <input type = "text" name = "primary" id = "primary" value = "{{single_hero.primary_ability}}"><br />
        New Secondary Ability: <input type = "text" name = "secondary" id = "secondary" value = "{{single_hero.secondary_ability}}"><br />
        New Catchphrase: <input type = "text" name = "catchphrase" id = "catch_phrase" value = "{{single_hero.catch_phrase}}"><br />
        <input type = "submit" value = "Edit!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes %}
        <li> <h2>{{hero.name}} - <a href = "{% url 'superheroes:detail' hero.id %}">Click for Details</a> - <a href = "{% url 'superheroes:edit' hero.id %}">Edit Superhero</a> - <a href = "{% url 'superheroes:delete' hero.id %}">Delete Superhero</a></h2> </li>
        {% endfor %}
    </ul>
    <a href = "{% url 'superheroes:create' %}">Add New Hero</a>
    <img src = "{% static 'superheroes/spiderman.png' %}" alt = "SpiderMan">
</body>
</html>